apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator-service
  template:
    metadata:
      labels:
        app: aggregator-service
    spec:
      containers:
        - name: aggregator-service
          image: us-central1-docker.pkg.dev/moon-insurance-project/moon-insurance-repo/aggregator-service:latest
          # image: aggregator-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5004
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mooninsurance-secrets
                  key: mongo-uri