apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  # namespace: mooninsurance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          # image: us-central1-docker.pkg.dev/moon-insurance-project/moon-insurance-repo/notification-service:latest
          image: us-central1-docker.pkg.dev/moon-insurance-project/moon-insurance-project/notification-service:latest
          # image: notification-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5003
              protocol: TCP
          env:
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: mooninsurance-secrets
                key: mongo-uri