apiVersion: apps/v1
kind: Deployment
metadata:
  name: redshift-analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redshift-analytics-service
  template:
    metadata:
      labels:
        app: redshift-analytics-service
    spec:
      containers:
        - name: redshift-analytics-service
          image: us-central1-docker.pkg.dev/moon-insurance-project/moon-insurance-repo/redshift-analytics-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5005
          env:
            - name: REDSHIFT_HOST
              valueFrom:
                secretKeyRef:
                  name: mooninsurance-secrets
                  key: redshift-host
            - name: REDSHIFT_PORT
              valueFrom:
                secretKeyRef:
                  name: mooninsurance-secrets
                  key: redshift-port
            - name: REDSHIFT_USER
              valueFrom:
                secretKeyRef:
                  name: mooninsurance-secrets
                  key: redshift-user
            - name: REDSHIFT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mooninsurance-secrets
                  key: redshift-password
            - name: REDSHIFT_DBNAME
              valueFrom:
                secretKeyRef:
                  name: mooninsurance-secrets
                  key: redshift-dbname
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mooninsurance-secrets
                  key: mongo-uri
      restartPolicy: Always
