apiVersion: v1
kind: Service
metadata:
  name: redshift-analytics-service
  namespace: mooninsurance
spec:
  selector:
    app: redshift-analytics
  ports:
    - protocol: TCP
      port: 5005
  type: ClusterIP