apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integration-service
  template:
    metadata:
      labels:
        app: integration-service
    spec:
      containers:
        - name: integration-service
          image: integration-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5002
          env:
            - name: MONGO_URI
              value: "YOUR_MONGO_URI_PLACEHOLDER"
