apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integration-service
  template:
    metadata:
      labels:
        app: integration-service
    spec:
      containers:
        - name: integration-service
          image: us-central1-docker.pkg.dev/moon-insurance-project/moon-insurance-repo/integration-service:latest
          # image: integration-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5002
          env:
            - name: MONGO_URI
              # value: mongodb://mongodb-service:27017
              # value: "${{ secrets.MONGO_URI }}"
      # restartPolicy: Always
          # env:
          #   - name: MONGO_URI
              value: "${MONGO_URI}"