apiVersion: v1
kind: Service
metadata:
  name: integration-service
spec:
  type: ClusterIP
  selector:
    app: integration-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
